# Generated by Django 5.1 on 2025-11-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PChop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', to='app_PChop.producto'),
        ),
    ]
